name: Generate Directory Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Directory Listing
        uses: gacts/directory-listing@v1
        with:
          target: './index.html'
          ignore: '[]' # Add this line

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update directory index"
