name: Generate Directory Index

on:
  push:
    branches:
      - main  # Or whichever branch your GitHub Pages is served from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Directory Listing
        uses: gacts/directory-listing@v1
        with:
          # The directory to generate the index for
          target: './'
          
          # The path for the generated index file
          output: 'index.html'

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update directory index"
